import { ContactField } from './types';

export const AVAILABLE_FIELDS: ContactField[] = [
  { value: 'first_name', label: 'First Name', required: true },
  { value: 'last_name', label: 'Last Name', required: false },
  { value: 'organization', label: 'Organization', required: false },
  { value: 'job_title', label: 'Job Title', required: false },
  { value: 'department', label: 'Department', required: false },
  { value: 'contact_type', label: 'Contact Type', required: false },
  { value: 'email', label: 'Email Address', required: false },
  { value: 'phone', label: 'Phone Number', required: false },
  { value: 'mobile', label: 'Mobile Number', required: false },
  { value: 'notes', label: 'Notes', required: false },
  { value: 'tags', label: 'Tags (semicolon separated)', required: false },
];

export const CONTACT_TEMPLATE_HEADERS = [
  'first_name',
  'last_name',
  'organization',
  'job_title',
  'department',
  'contact_type',
  'email',
  'phone',
  'mobile',
  'notes',
  'tags',
];

export const CONTACT_TEMPLATE_SAMPLE_ROWS = [
  [
    'John',
    'Smith',
    'Acme Corporation',
    'Software Engineer',
    'Engineering',
    'internal',
    'john.smith@acme.com',
    '+1-555-0123',
    '+1-555-0124',
    'Lead developer for project X',
    'developer;team-lead;javascript',
  ],
  [
    'Jane',
    'Doe',
    'Tech Solutions Inc',
    'Product Manager',
    'Product',
    'external',
    'jane.doe@techsolutions.com',
    '+1-555-0125',
    '',
    'External consultant for Q1 project',
    'consultant;product;external',
  ],
  [
    'Michael',
    'Johnson',
    'ABC Company',
    'Sales Director',
    'Sales',
    'customer',
    'mjohnson@abc.com',
    '+1-555-0126',
    '+1-555-0127',
    'Key account manager',
    'sales;customer;vip',
  ],
];
